#!/usr/bin/env python3
"""Retarget ManiSkill Panda demonstrations into robosuite / MuJoCo.

This is a cross-simulator trajectory retargeter, not a lossless converter.
ManiSkill joint-position targets are tracked by a robosuite Panda in MuJoCo and
the resulting MuJoCo states, observations, actions, and wrist wrench are saved
in robomimic-compatible HDF5 format.

The wrench samples are generated by MuJoCo. They are not measurements recovered
from PhysX and are meaningful only to the extent that the selected robosuite
task, geometry, controller, and trajectory reproduce the intended interaction.
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Iterable

# Make the standalone environment package importable when this file is run as
# ``python scripts/...`` without installing the LIBERO repository itself.
REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
if str(REPOSITORY_ROOT) not in sys.path:
    sys.path.insert(0, str(REPOSITORY_ROOT))

import h5py
import numpy as np
import robosuite as suite
from robosuite.controllers import load_controller_config

# Registers the standalone ports. This package does not touch LIBERO BDDL tasks.
import maniskill_mujoco_envs  # noqa: F401


FORCE_KEY = "robot0_eef_force"
TORQUE_KEY = "robot0_eef_torque"


@dataclass(frozen=True)
class TaskMapping:
    env_name: str
    object_map: tuple[tuple[str, str], ...]
    fidelity: str


# Values on the right name attributes on the corresponding robosuite env.
TASK_MAPPINGS: dict[str, TaskMapping] = {
    "PickCube-v1": TaskMapping(
        "ManiSkillMujocoPickCube",
        (("cube", "cube"), ("goal_site", "goal_site")),
        "procedural_port",
    ),
    "StackCube-v1": TaskMapping(
        "ManiSkillMujocoStackCube",
        (("cubeA", "cubeA"), ("cubeB", "cubeB")),
        "procedural_port",
    ),
    "StackPyramid-v1": TaskMapping(
        "ManiSkillMujocoStackPyramid",
        (("cubeA", "cubeA"), ("cubeB", "cubeB"), ("cubeC", "cubeC")),
        "procedural_port",
    ),
    "PegInsertionSide-v1": TaskMapping(
        "ManiSkillMujocoPegInsertionSide",
        (("peg", "peg"), ("box_with_hole", "box_with_hole")),
        "procedural_port",
    ),
    "PlugCharger-v1": TaskMapping(
        "ManiSkillMujocoPlugCharger",
        (("charger", "charger"), ("receptacle", "receptacle")),
        "procedural_port",
    ),
}


def natural_trajectory_key(name: str) -> tuple[str, int | str]:
    prefix, separator, suffix = name.rpartition("_")
    return (prefix, int(suffix)) if separator and suffix.isdigit() else (name, name)


def task_id_from_path(path: Path) -> str:
    for parent in path.resolve().parents:
        if parent.name in TASK_MAPPINGS:
            return parent.name
    raise ValueError(
        f"could not infer ManiSkill task from {path}; pass --task-id explicitly"
    )


def source_episode_metadata(json_path: Path) -> dict[int, dict[str, Any]]:
    if not json_path.is_file():
        raise FileNotFoundError(
            f"ManiSkill requires the matching metadata file next to the HDF5: {json_path}"
        )
    with json_path.open("r", encoding="utf-8") as stream:
        payload = json.load(stream)
    episodes = payload.get("episodes", payload) if isinstance(payload, dict) else payload
    if not isinstance(episodes, list):
        raise ValueError(f"unexpected ManiSkill metadata structure in {json_path}")
    return {int(item["episode_id"]): item for item in episodes}


def make_environment(env_name: str, control_freq: int):
    controller = load_controller_config(default_controller="JOINT_POSITION")
    return suite.make(
        env_name=env_name,
        robots="Panda",
        controller_configs=controller,
        gripper_types="PandaGripper",
        has_renderer=False,
        has_offscreen_renderer=False,
        use_camera_obs=False,
        use_object_obs=True,
        reward_shaping=False,
        control_freq=control_freq,
        hard_reset=False,
        ignore_done=True,
    )


def source_actor_poses(trajectory: h5py.Group) -> dict[str, np.ndarray]:
    actors = trajectory.get("env_states/actors")
    if actors is None:
        return {}
    poses: dict[str, np.ndarray] = {}
    for name, dataset in actors.items():
        state = np.asarray(dataset[0], dtype=np.float64)
        if state.size >= 7:
            # ManiSkill actor state starts with xyz + quaternion (wxyz).
            poses[name] = state[:7]
    return poses


def resolve_robosuite_object(env, attribute: str):
    if attribute == "first_nut":
        nuts = getattr(env, "nuts", ())
        return nuts[0] if nuts else None
    return getattr(env, attribute, None)


def copy_initial_object_poses(
    env,
    source_poses: dict[str, np.ndarray],
    object_map: Iterable[tuple[str, str]],
) -> int:
    """Copy relative source object layout while anchoring the first target object.

    Absolute world frames differ between SAPIEN and MuJoCo. The first mapped
    source object is translated to the current target object position; the same
    translation is then applied to the remaining mapped objects. Orientations
    are copied directly because both state formats use wxyz quaternions.
    """
    resolved: list[tuple[np.ndarray, Any, str]] = []
    for source_name, target_attribute in object_map:
        if source_name not in source_poses:
            continue
        if hasattr(env, "get_task_object_pose"):
            try:
                env.get_task_object_pose(target_attribute)
            except KeyError:
                continue
            resolved.append((source_poses[source_name], None, target_attribute))
            continue
        target = resolve_robosuite_object(env, target_attribute)
        if target is not None and target.joints:
            resolved.append((source_poses[source_name], target, target_attribute))
    if not resolved:
        return 0

    first_source, first_target, first_name = resolved[0]
    if hasattr(env, "source_world_offset"):
        translation = np.asarray(env.source_world_offset, dtype=np.float64)
    elif hasattr(env, "get_task_object_pose"):
        first_target_qpos = env.get_task_object_pose(first_name)
        translation = first_target_qpos[:3] - first_source[:3]
    else:
        first_target_qpos = np.asarray(env.sim.data.get_joint_qpos(first_target.joints[0]))
        translation = first_target_qpos[:3] - first_source[:3]
    for source_pose, target, target_name in resolved:
        target_qpos = np.concatenate((source_pose[:3] + translation, source_pose[3:7]))
        if hasattr(env, "set_task_object_pose"):
            env.set_task_object_pose(target_name, target_qpos)
        else:
            env.sim.data.set_joint_qpos(target.joints[0], target_qpos)
    env.sim.forward()
    return len(resolved)


def set_initial_robot_configuration(env, source_target: np.ndarray) -> None:
    robot = env.robots[0]
    if source_target.size < 7:
        raise ValueError(f"expected at least 7 Panda joint targets, got {source_target.size}")
    env.sim.data.qpos[robot._ref_joint_pos_indexes] = source_target[:7]
    env.sim.data.qvel[robot._ref_joint_vel_indexes] = 0.0
    env.sim.forward()
    robot.controller.reset_goal()


def scaled_joint_action(controller, target_qpos: np.ndarray, current_qpos: np.ndarray) -> np.ndarray:
    """Map an absolute Panda qpos target to robosuite's normalized delta action."""
    delta = np.asarray(target_qpos) - np.asarray(current_qpos)
    output_max = np.asarray(controller.output_max, dtype=np.float64)
    output_min = np.asarray(controller.output_min, dtype=np.float64)
    input_max = np.asarray(controller.input_max, dtype=np.float64)
    input_min = np.asarray(controller.input_min, dtype=np.float64)
    positive = delta / np.maximum(output_max, 1e-12) * input_max
    negative = delta / np.maximum(np.abs(output_min), 1e-12) * np.abs(input_min)
    action = np.where(delta >= 0.0, positive, negative)
    return np.clip(action, input_min, input_max)


def retarget_action(env, source_action: np.ndarray, invert_gripper: bool) -> np.ndarray:
    robot = env.robots[0]
    arm_action = scaled_joint_action(
        robot.controller,
        np.asarray(source_action[:7], dtype=np.float64),
        np.asarray(robot._joint_positions, dtype=np.float64),
    )
    # ManiSkill Panda demos use +1=open / -1=closed; robosuite Panda uses the inverse.
    source_gripper = float(source_action[7]) if source_action.size > 7 else 1.0
    gripper_action = -source_gripper if invert_gripper else source_gripper
    return np.concatenate((arm_action, [np.clip(gripper_action, -1.0, 1.0)]))


def numeric_observation(obs: dict[str, Any], env) -> dict[str, np.ndarray]:
    result: dict[str, np.ndarray] = {}
    for key, value in obs.items():
        array = np.asarray(value)
        if array.dtype.kind in "biuf" and array.ndim > 0:
            result[key] = array.astype(np.float32, copy=False)
    robot = env.robots[0]
    result[FORCE_KEY] = np.asarray(robot.ee_force, dtype=np.float32).copy()
    result[TORQUE_KEY] = np.asarray(robot.ee_torque, dtype=np.float32).copy()
    return result


def stack_observations(items: list[dict[str, np.ndarray]]) -> dict[str, np.ndarray]:
    if not items:
        return {}
    common = set(items[0]).intersection(*(set(item) for item in items[1:]))
    return {key: np.stack([item[key] for item in items]) for key in sorted(common)}


def write_observation_group(parent: h5py.Group, name: str, items: list[dict[str, np.ndarray]]) -> None:
    group = parent.create_group(name)
    for key, values in stack_observations(items).items():
        group.create_dataset(key, data=values, compression="gzip")


def replay_trajectory(
    env,
    source: h5py.Group,
    mapping: TaskMapping,
    invert_gripper: bool,
    copy_object_poses: bool,
) -> dict[str, Any]:
    source_actions = np.asarray(source["actions"], dtype=np.float32)
    if source_actions.ndim != 2 or source_actions.shape[1] < 7:
        raise ValueError(f"unsupported source action shape {source_actions.shape}")

    reset_obs = env.reset()
    copied_objects = 0
    if copy_object_poses:
        copied_objects = copy_initial_object_poses(
            env, source_actor_poses(source), mapping.object_map
        )
    set_initial_robot_configuration(env, source_actions[0])
    reset_obs = env._get_observations(force_update=True)

    states: list[np.ndarray] = []
    observations: list[dict[str, np.ndarray]] = []
    next_observations: list[dict[str, np.ndarray]] = []
    mujoco_actions: list[np.ndarray] = []
    rewards: list[float] = []
    dones: list[bool] = []
    tracking_errors: list[np.ndarray] = []

    current_obs = reset_obs
    for source_action in source_actions:
        states.append(np.asarray(env.sim.get_state().flatten(), dtype=np.float64))
        observations.append(numeric_observation(current_obs, env))
        action = retarget_action(env, source_action, invert_gripper)
        next_obs, reward, done, _ = env.step(action)
        next_observations.append(numeric_observation(next_obs, env))
        mujoco_actions.append(action.astype(np.float32))
        rewards.append(float(reward))
        dones.append(bool(done))
        tracking_errors.append(
            np.asarray(source_action[:7] - env.robots[0]._joint_positions, dtype=np.float32)
        )
        current_obs = next_obs

    return {
        "states": np.asarray(states),
        "actions": np.asarray(mujoco_actions),
        "source_actions": source_actions,
        "rewards": np.asarray(rewards, dtype=np.float32),
        "dones": np.asarray(dones, dtype=np.bool_),
        "tracking_error": np.asarray(tracking_errors, dtype=np.float32),
        "obs": observations,
        "next_obs": next_observations,
        "copied_objects": copied_objects,
    }


def output_env_metadata(env, env_name: str, control_freq: int) -> str:
    try:
        return json.dumps(env.serialize(), sort_keys=True)
    except (AttributeError, TypeError):
        return json.dumps(
            {
                "env_name": env_name,
                "type": 1,
                "env_kwargs": {
                    "robots": ["Panda"],
                    "controller_configs": load_controller_config(
                        default_controller="JOINT_POSITION"
                    ),
                    "gripper_types": "PandaGripper",
                    "use_camera_obs": False,
                    "use_object_obs": True,
                    "reward_shaping": False,
                    "control_freq": control_freq,
                },
            },
            sort_keys=True,
        )


def convert(args: argparse.Namespace) -> None:
    input_path = args.input.resolve()
    if not input_path.is_file():
        raise FileNotFoundError(input_path)
    task_id = args.task_id or task_id_from_path(input_path)
    mapping = TASK_MAPPINGS.get(task_id)
    if mapping is None:
        raise ValueError(
            f"no default mapping for {task_id}; supported: {', '.join(TASK_MAPPINGS)}"
        )
    if args.env_name:
        mapping = TaskMapping(args.env_name, mapping.object_map, "user_override")

    metadata = source_episode_metadata(input_path.with_suffix(".json"))
    env = make_environment(mapping.env_name, args.control_freq)
    output_path = args.output.resolve()
    output_path.parent.mkdir(parents=True, exist_ok=True)
    temporary_path = output_path.with_name(f".{output_path.name}.tmp")
    if temporary_path.exists():
        temporary_path.unlink()

    total = 0
    try:
        with h5py.File(input_path, "r") as source_file, h5py.File(temporary_path, "w") as output_file:
            data = output_file.create_group("data")
            data.attrs["env_args"] = output_env_metadata(
                env, mapping.env_name, args.control_freq
            )
            data.attrs["env_meta"] = data.attrs["env_args"]
            data.attrs["source_task"] = task_id
            data.attrs["target_env"] = mapping.env_name
            data.attrs["environment_label"] = getattr(
                env, "environment_label", mapping.env_name
            )
            data.attrs["environment_family"] = "maniskill_mujoco_port"
            data.attrs["retarget_fidelity"] = mapping.fidelity
            data.attrs["source_file"] = str(input_path)
            data.attrs["wrench_frame"] = "robosuite Panda gripper force/torque sensor frame"
            data.attrs["wrench_units"] = "N,Nm"
            data.attrs["cross_simulation"] = True

            keys = sorted(
                (key for key in source_file if key.startswith("traj_")),
                key=natural_trajectory_key,
            )
            if args.count is not None:
                keys = keys[: args.count]
            if not keys:
                raise ValueError(f"no traj_* groups found in {input_path}")

            for output_index, source_key in enumerate(keys):
                episode_id = int(source_key.rsplit("_", 1)[1])
                episode_metadata = metadata.get(episode_id, {})
                if hasattr(env, "configure_source_episode"):
                    env.configure_source_episode(episode_metadata)
                result = replay_trajectory(
                    env,
                    source_file[source_key],
                    mapping,
                    invert_gripper=not args.no_invert_gripper,
                    copy_object_poses=not args.no_copy_object_poses,
                )
                demo = data.create_group(f"demo_{output_index}")
                for key in (
                    "states",
                    "actions",
                    "source_actions",
                    "rewards",
                    "dones",
                    "tracking_error",
                ):
                    demo.create_dataset(key, data=result[key], compression="gzip")
                write_observation_group(demo, "obs", result["obs"])
                write_observation_group(demo, "next_obs", result["next_obs"])
                samples = len(result["actions"])
                demo.attrs["num_samples"] = samples
                demo.attrs["source_trajectory"] = source_key
                demo.attrs["source_episode_metadata"] = json.dumps(
                    episode_metadata, sort_keys=True
                )
                demo.attrs["copied_source_object_poses"] = result["copied_objects"]
                try:
                    demo.attrs["model_file"] = env.model.get_xml()
                except AttributeError:
                    pass
                total += samples
                max_error = float(np.max(np.abs(result["tracking_error"])))
                print(
                    f"{source_key} -> demo_{output_index}: {samples} steps, "
                    f"max joint error={max_error:.4f} rad"
                )

            data.attrs["total"] = total
            data.attrs["num_demos"] = len(keys)
            output_file.flush()
        os.replace(temporary_path, output_path)
    except BaseException:
        if temporary_path.exists():
            temporary_path.unlink()
        raise
    finally:
        env.close()

    print(f"Wrote {len(keys)} demos / {total} samples to {output_path}")
    if mapping.fidelity != "procedural_port":
        print(f"WARNING: {task_id} uses {mapping.env_name} with fidelity={mapping.fidelity}")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", type=Path, required=True, help="ManiSkill trajectory.h5")
    parser.add_argument("--output", type=Path, required=True, help="Output robomimic HDF5")
    parser.add_argument("--task-id", help="Override task inferred from the input path")
    parser.add_argument("--env-name", help="Override the mapped robosuite environment")
    parser.add_argument("--count", type=int, help="Only convert the first N trajectories")
    parser.add_argument("--control-freq", type=int, default=20)
    parser.add_argument(
        "--no-invert-gripper",
        action="store_true",
        help="Do not map ManiSkill +1=open to robosuite -1=open",
    )
    parser.add_argument(
        "--no-copy-object-poses",
        action="store_true",
        help="Keep robosuite's sampled initial object poses",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    if args.count is not None and args.count <= 0:
        raise ValueError("--count must be positive")
    convert(args)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
