#!/usr/bin/env python3
"""Convert ManiSkill Panda demonstrations into robosuite / MuJoCo HDF5.

This is a cross-simulator trajectory retargeter, not a lossless converter.
ManiSkill joint-position targets are tracked by a robosuite Panda in MuJoCo and
By default, every recorded PhysX state is mapped into the faithful MuJoCo task
port. This avoids accumulating cross-simulator contact and controller drift.
The resulting MuJoCo states, observations, actions, and wrist wrench are saved
in robomimic / MimicGen-compatible HDF5 format. An open-loop replay mode is
also available for measuring cross-simulator reproducibility.

The wrench samples are generated by MuJoCo. They are not measurements recovered
from PhysX and are meaningful only to the extent that the selected robosuite
task, geometry, controller, and trajectory reproduce the intended interaction.
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Iterable

# Make the standalone environment package importable when this file is run as
# ``python scripts/...`` without installing the LIBERO repository itself.
REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
if str(REPOSITORY_ROOT) not in sys.path:
    sys.path.insert(0, str(REPOSITORY_ROOT))

import h5py
import mujoco
import numpy as np
import robosuite as suite
from robosuite.controllers import load_controller_config
from robosuite.utils import transform_utils as T

# Registers the standalone ports. This package does not touch LIBERO BDDL tasks.
import maniskill_mujoco_envs  # noqa: F401
from maniskill_mujoco_envs.wrapper import ManiSkillWrapper


FORCE_KEY = "robot0_eef_force"
TORQUE_KEY = "robot0_eef_torque"


@dataclass(frozen=True)
class TaskMapping:
    env_name: str
    object_map: tuple[tuple[str, str], ...]
    fidelity: str


# Values on the right name attributes on the corresponding robosuite env.
TASK_MAPPINGS: dict[str, TaskMapping] = {
    "PickCube-v1": TaskMapping(
        "ManiSkillMujocoPickCube",
        (("cube", "cube"), ("goal_site", "goal_site")),
        "procedural_port",
    ),
    "StackCube-v1": TaskMapping(
        "ManiSkillMujocoStackCube",
        (("cubeA", "cubeA"), ("cubeB", "cubeB")),
        "procedural_port",
    ),
    "StackPyramid-v1": TaskMapping(
        "ManiSkillMujocoStackPyramid",
        (("cubeA", "cubeA"), ("cubeB", "cubeB"), ("cubeC", "cubeC")),
        "procedural_port",
    ),
    "PegInsertionSide-v1": TaskMapping(
        "ManiSkillMujocoPegInsertionSide",
        (("peg", "peg"), ("box_with_hole", "box_with_hole")),
        "procedural_port",
    ),
    "PlugCharger-v1": TaskMapping(
        "ManiSkillMujocoPlugCharger",
        (("charger", "charger"), ("receptacle", "receptacle")),
        "procedural_port",
    ),
}


def natural_trajectory_key(name: str) -> tuple[str, int | str]:
    prefix, separator, suffix = name.rpartition("_")
    return (prefix, int(suffix)) if separator and suffix.isdigit() else (name, name)


def task_id_from_path(path: Path) -> str:
    for parent in path.resolve().parents:
        if parent.name in TASK_MAPPINGS:
            return parent.name
    raise ValueError(
        f"could not infer ManiSkill task from {path}; pass --task-id explicitly"
    )


def source_episode_metadata(json_path: Path) -> dict[int, dict[str, Any]]:
    if not json_path.is_file():
        raise FileNotFoundError(
            f"ManiSkill requires the matching metadata file next to the HDF5: {json_path}"
        )
    with json_path.open("r", encoding="utf-8") as stream:
        payload = json.load(stream)
    episodes = payload.get("episodes", payload) if isinstance(payload, dict) else payload
    if not isinstance(episodes, list):
        raise ValueError(f"unexpected ManiSkill metadata structure in {json_path}")
    return {int(item["episode_id"]): item for item in episodes}


def make_environment(
    env_name: str, control_freq: int, controller: str = "JOINT_POSITION",
    joint_kp: float | None = None, joint_damping_ratio: float | None = None,
):
    controller_config = load_controller_config(default_controller=controller)
    if controller == "JOINT_POSITION" and joint_kp is not None:
        controller_config["kp"] = joint_kp
    if controller == "JOINT_POSITION" and joint_damping_ratio is not None:
        controller_config["damping_ratio"] = joint_damping_ratio
    return suite.make(
        env_name=env_name,
        robots="Panda",
        controller_configs=controller_config,
        gripper_types="PandaGripper",
        has_renderer=False,
        has_offscreen_renderer=False,
        use_camera_obs=False,
        use_object_obs=True,
        reward_shaping=False,
        control_freq=control_freq,
        hard_reset=False,
        ignore_done=True,
    )


def source_actor_poses(trajectory: h5py.Group) -> dict[str, np.ndarray]:
    actors = trajectory.get("env_states/actors")
    if actors is None:
        return {}
    poses: dict[str, np.ndarray] = {}
    for name, dataset in actors.items():
        state = np.asarray(dataset[0], dtype=np.float64)
        if state.size >= 7:
            # ManiSkill actor state starts with xyz + quaternion (wxyz).
            poses[name] = state[:7]
    return poses


def source_articulation_states(trajectory: h5py.Group) -> np.ndarray:
    articulations = trajectory.get("env_states/articulations")
    if articulations is None or len(articulations) != 1:
        names = [] if articulations is None else list(articulations)
        raise ValueError(f"expected one Panda articulation, found {names}")
    return np.asarray(articulations[next(iter(articulations))], dtype=np.float64)


def source_actor_states(trajectory: h5py.Group) -> dict[str, np.ndarray]:
    actors = trajectory.get("env_states/actors")
    if actors is None:
        return {}
    return {name: np.asarray(value, dtype=np.float64) for name, value in actors.items()}


def resolve_robosuite_object(env, attribute: str):
    if attribute == "first_nut":
        nuts = getattr(env, "nuts", ())
        return nuts[0] if nuts else None
    return getattr(env, attribute, None)


def copy_initial_object_poses(
    env,
    source_poses: dict[str, np.ndarray],
    object_map: Iterable[tuple[str, str]],
) -> int:
    """Copy relative source object layout while anchoring the first target object.

    Absolute world frames differ between SAPIEN and MuJoCo. The first mapped
    source object is translated to the current target object position; the same
    translation is then applied to the remaining mapped objects. Orientations
    are copied directly because both state formats use wxyz quaternions.
    """
    resolved: list[tuple[np.ndarray, Any, str]] = []
    for source_name, target_attribute in object_map:
        if source_name not in source_poses:
            continue
        if hasattr(env, "get_task_object_pose"):
            try:
                env.get_task_object_pose(target_attribute)
            except KeyError:
                continue
            resolved.append((source_poses[source_name], None, target_attribute))
            continue
        target = resolve_robosuite_object(env, target_attribute)
        if target is not None and target.joints:
            resolved.append((source_poses[source_name], target, target_attribute))
    if not resolved:
        return 0

    first_source, first_target, first_name = resolved[0]
    if hasattr(env, "source_world_offset"):
        translation = np.asarray(env.source_world_offset, dtype=np.float64)
    elif hasattr(env, "get_task_object_pose"):
        first_target_qpos = env.get_task_object_pose(first_name)
        translation = first_target_qpos[:3] - first_source[:3]
    else:
        first_target_qpos = np.asarray(env.sim.data.get_joint_qpos(first_target.joints[0]))
        translation = first_target_qpos[:3] - first_source[:3]
    for source_pose, target, target_name in resolved:
        target_qpos = np.concatenate((source_pose[:3] + translation, source_pose[3:7]))
        if hasattr(env, "set_task_object_pose"):
            env.set_task_object_pose(target_name, target_qpos)
        else:
            env.sim.data.set_joint_qpos(target.joints[0], target_qpos)
    env.sim.forward()
    return len(resolved)


def set_initial_robot_configuration(env, source_target: np.ndarray) -> None:
    robot = env.robots[0]
    if source_target.size < 7:
        raise ValueError(f"expected at least 7 Panda joint targets, got {source_target.size}")
    env.sim.data.qpos[robot._ref_joint_pos_indexes] = source_target[:7]
    env.sim.data.qvel[robot._ref_joint_vel_indexes] = 0.0
    env.sim.forward()
    robot.controller.reset_goal()


def set_mapped_state(
    env,
    articulation: np.ndarray,
    actors: dict[str, np.ndarray],
    object_map: Iterable[tuple[str, str]],
) -> None:
    """Install one recorded ManiSkill state in the corresponding MuJoCo model.

    ManiSkill articulation state layout is root pose (7), root velocities (6),
    joint positions (9), then joint velocities (9). Actor state layout is pose
    (7), linear velocity (3), and angular velocity (3).
    """
    if articulation.size < 31:
        raise ValueError(f"unsupported articulation state shape {articulation.shape}")
    robot = env.robots[0]
    joint_qpos = articulation[13:22]
    joint_qvel = articulation[22:31]
    env.sim.data.qpos[robot._ref_joint_pos_indexes] = joint_qpos[:7]
    env.sim.data.qvel[robot._ref_joint_vel_indexes] = joint_qvel[:7]
    # ManiSkill's URDF represents both finger openings as positive values.
    # robosuite's Panda MJCF uses +q for finger 1 but -q for finger 2
    # (ranges [0, .04] and [-.04, 0], respectively).
    env.sim.data.qpos[robot._ref_gripper_joint_pos_indexes] = (
        joint_qpos[7], -joint_qpos[8]
    )
    env.sim.data.qvel[robot._ref_gripper_joint_vel_indexes] = (
        joint_qvel[7], -joint_qvel[8]
    )

    for source_name, target_name in object_map:
        if source_name not in actors or target_name not in env.task_objects:
            continue
        state = actors[source_name]
        pose = state[:7].copy()
        pose[:3] += np.asarray(env.source_world_offset, dtype=np.float64)
        env.set_task_object_pose(target_name, pose)
        if target_name in env.dynamic_object_names and state.size >= 13:
            joint_name = env.task_objects[target_name].joints[0]
            velocity_address = env.sim.model.get_joint_qvel_addr(joint_name)
            start = velocity_address[0] if isinstance(velocity_address, tuple) else velocity_address
            env.sim.data.qvel[start : start + 6] = state[7:13]
    env.sim.forward()
    synchronize_gripper_command_state(env)


def synchronize_gripper_command_state(env) -> None:
    """Align robosuite's hidden gripper command state after a state install.

    PandaGripper integrates binary open / close commands in normalized actuator
    space. Teleporting finger qpos without updating ``current_action`` makes the
    next command start from a stale target, unlike ManiSkill's absolute gripper
    position controller.
    """
    robot = env.robots[0]
    actuator_ids = robot._ref_joint_gripper_actuator_indexes
    qpos = np.asarray(
        env.sim.data.qpos[robot._ref_gripper_joint_pos_indexes], dtype=np.float64
    )
    control_range = np.asarray(env.sim.model.actuator_ctrlrange[actuator_ids])
    midpoint = 0.5 * (control_range[:, 0] + control_range[:, 1])
    half_range = 0.5 * (control_range[:, 1] - control_range[:, 0])
    robot.gripper.current_action = np.clip((qpos - midpoint) / half_range, -1.0, 1.0)


def scaled_joint_action(controller, target_qpos: np.ndarray, current_qpos: np.ndarray) -> np.ndarray:
    """Map an absolute Panda qpos target to robosuite's normalized delta action."""
    delta = np.asarray(target_qpos) - np.asarray(current_qpos)
    output_max = np.asarray(controller.output_max, dtype=np.float64)
    output_min = np.asarray(controller.output_min, dtype=np.float64)
    input_max = np.asarray(controller.input_max, dtype=np.float64)
    input_min = np.asarray(controller.input_min, dtype=np.float64)
    positive = delta / np.maximum(output_max, 1e-12) * input_max
    negative = delta / np.maximum(np.abs(output_min), 1e-12) * np.abs(input_min)
    action = np.where(delta >= 0.0, positive, negative)
    return np.clip(action, input_min, input_max)


def retarget_action(env, source_action: np.ndarray, invert_gripper: bool) -> np.ndarray:
    robot = env.robots[0]
    arm_action = scaled_joint_action(
        robot.controller,
        np.asarray(source_action[:7], dtype=np.float64),
        np.asarray(robot._joint_positions, dtype=np.float64),
    )
    # ManiSkill Panda demos use +1=open / -1=closed; robosuite Panda uses the inverse.
    source_gripper = float(source_action[7]) if source_action.size > 7 else 1.0
    gripper_action = -source_gripper if invert_gripper else source_gripper
    return np.concatenate((arm_action, [np.clip(gripper_action, -1.0, 1.0)]))


def numeric_observation(obs: dict[str, Any], env) -> dict[str, np.ndarray]:
    result: dict[str, np.ndarray] = {}
    for key, value in obs.items():
        array = np.asarray(value)
        if array.dtype.kind in "biuf" and array.ndim > 0:
            result[key] = array.astype(np.float32, copy=False)
    robot = env.robots[0]
    result[FORCE_KEY] = np.asarray(robot.ee_force, dtype=np.float32).copy()
    result[TORQUE_KEY] = np.asarray(robot.ee_torque, dtype=np.float32).copy()
    joint = np.asarray(robot._joint_positions, dtype=np.float32).copy()
    gripper = np.asarray(
        env.sim.data.qpos[robot._ref_gripper_joint_pos_indexes], dtype=np.float32
    ).copy()
    ee_pos = np.asarray(obs.get("robot0_eef_pos", robot._hand_pos), dtype=np.float32).copy()
    ee_quat = np.asarray(obs.get("robot0_eef_quat", T.mat2quat(robot._hand_orn)))
    ee_ori = np.asarray(T.quat2axisangle(ee_quat), dtype=np.float32)
    left, right = finger_contact_forces(env)
    result.update(
        joint_states=joint,
        gripper_states=gripper,
        ee_pos=ee_pos,
        ee_ori=ee_ori,
        ee_states=np.concatenate((ee_pos, ee_ori)),
        ee_force=result[FORCE_KEY],
        ee_torque=result[TORQUE_KEY],
        left_gripper_force=np.asarray([left], dtype=np.float32),
        right_gripper_force=np.asarray([right], dtype=np.float32),
    )
    return result


def finger_contact_forces(env) -> tuple[float, float]:
    names = env.robots[0].gripper.contact_geoms
    geom_ids = [
        {env.sim.model.geom_name2id(name) for name in names if f"finger{side}" in name}
        for side in (1, 2)
    ]
    result = [0.0, 0.0]
    wrench = np.zeros(6)
    for index in range(env.sim.data.ncon):
        contact = env.sim.data.contact[index]
        for side, ids in enumerate(geom_ids):
            if contact.geom1 in ids or contact.geom2 in ids:
                mujoco.mj_contactForce(env.sim.model._model, env.sim.data._data, index, wrench)
                result[side] += abs(float(wrench[0]))
    return result[0], result[1]


def configure_contact_physics(
    env, surface_friction: float, finger_friction: float, contact_timeconstant: float,
    gripper_force_limit: float,
) -> None:
    """Match the principal PhysX material and contact-response parameters."""
    finger_names = set(env.robots[0].gripper.contact_geoms)
    for geom_id in range(env.sim.model.ngeom):
        if env.sim.model.geom_contype[geom_id] == 0:
            continue
        name = env.sim.model.geom_id2name(geom_id)
        sliding = finger_friction if name in finger_names else surface_friction
        env.sim.model.geom_friction[geom_id, 0] = sliding
        env.sim.model.geom_solref[geom_id] = (contact_timeconstant, 1.0)
        env.sim.model.geom_solimp[geom_id] = (0.95, 0.99, 1e-4, 0.5, 2.0)
    for actuator_id in env.robots[0]._ref_joint_gripper_actuator_indexes:
        env.sim.model.actuator_forcerange[actuator_id] = (
            -gripper_force_limit, gripper_force_limit
        )


def libero_actions(result: dict[str, Any]) -> np.ndarray:
    current = result["obs"]
    following = result["next_obs"]
    actions = np.empty((len(current), 7), dtype=np.float32)
    for index, (obs, next_obs) in enumerate(zip(current, following)):
        actions[index, :3] = np.clip((next_obs["ee_pos"] - obs["ee_pos"]) / 0.05, -1, 1)
        current_quat = obs["robot0_eef_quat"]
        next_quat = next_obs["robot0_eef_quat"]
        actions[index, 3:6] = np.clip(T.get_orientation_error(next_quat, current_quat) / 0.5, -1, 1)
        actions[index, 6] = result["actions"][index, -1]
    return actions


def stack_observations(items: list[dict[str, np.ndarray]]) -> dict[str, np.ndarray]:
    if not items:
        return {}
    common = set(items[0]).intersection(*(set(item) for item in items[1:]))
    return {key: np.stack([item[key] for item in items]) for key in sorted(common)}


def write_observation_group(parent: h5py.Group, name: str, items: list[dict[str, np.ndarray]]) -> None:
    group = parent.create_group(name)
    for key, values in stack_observations(items).items():
        group.create_dataset(key, data=values, compression="gzip")


def replay_trajectory(
    env,
    source: h5py.Group,
    mapping: TaskMapping,
    invert_gripper: bool,
    copy_object_poses: bool,
) -> dict[str, Any]:
    source_actions = np.asarray(source["actions"], dtype=np.float32)
    if source_actions.ndim != 2 or source_actions.shape[1] < 7:
        raise ValueError(f"unsupported source action shape {source_actions.shape}")

    reset_obs = env.reset()
    copied_objects = 0
    if copy_object_poses:
        copied_objects = copy_initial_object_poses(
            env, source_actor_poses(source), mapping.object_map
        )
    set_initial_robot_configuration(env, source_actions[0])
    reset_obs = env._get_observations(force_update=True)

    states: list[np.ndarray] = []
    observations: list[dict[str, np.ndarray]] = []
    next_observations: list[dict[str, np.ndarray]] = []
    mujoco_actions: list[np.ndarray] = []
    rewards: list[float] = []
    dones: list[bool] = []
    tracking_errors: list[np.ndarray] = []

    current_obs = reset_obs
    for source_action in source_actions:
        states.append(np.asarray(env.sim.get_state().flatten(), dtype=np.float64))
        observations.append(numeric_observation(current_obs, env))
        action = retarget_action(env, source_action, invert_gripper)
        next_obs, reward, done, _ = env.step(action)
        next_observations.append(numeric_observation(next_obs, env))
        mujoco_actions.append(action.astype(np.float32))
        rewards.append(float(reward))
        dones.append(bool(done))
        tracking_errors.append(
            np.asarray(source_action[:7] - env.robots[0]._joint_positions, dtype=np.float32)
        )
        current_obs = next_obs

    return {
        "states": np.asarray(states),
        "actions": np.asarray(mujoco_actions),
        "source_actions": source_actions,
        "rewards": np.asarray(rewards, dtype=np.float32),
        "dones": np.asarray(dones, dtype=np.bool_),
        "tracking_error": np.asarray(tracking_errors, dtype=np.float32),
        "obs": observations,
        "next_obs": next_observations,
        "copied_objects": copied_objects,
    }


def reference_tcp_poses(env, articulation: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
    """Evaluate the source Panda joint path as TCP poses in the target model."""
    if articulation.ndim != 2 or articulation.shape[1] < 22:
        raise ValueError(f"unsupported articulation state shape {articulation.shape}")
    robot = env.robots[0]
    saved_state = env.sim.get_state().flatten().copy()
    positions, quaternions = [], []
    try:
        for state in articulation:
            env.sim.data.qpos[robot._ref_joint_pos_indexes] = state[13:20]
            env.sim.data.qvel[robot._ref_joint_vel_indexes] = 0.0
            env.sim.forward()
            positions.append(np.asarray(env.sim.data.site_xpos[robot.eef_site_id], dtype=np.float64).copy())
            site_rotation = np.asarray(env.sim.data.site_xmat[robot.eef_site_id]).reshape(3, 3)
            quaternions.append(T.mat2quat(site_rotation).copy())
    finally:
        env.sim.set_state_from_flattened(saved_state)
        env.sim.forward()
    return np.asarray(positions), np.asarray(quaternions)


def osc_pose_action(
    current_obs, desired_position, desired_quaternion, gripper, tracking_gain=1.0
) -> np.ndarray:
    """Normalized OSC_POSE command from the actual TCP pose to a reference pose."""
    current_position = np.asarray(current_obs["robot0_eef_pos"], dtype=np.float64)
    current_quaternion = np.asarray(current_obs["robot0_eef_quat"], dtype=np.float64)
    position = np.clip(tracking_gain * (desired_position - current_position) / 0.05, -1.0, 1.0)
    orientation = np.clip(
        tracking_gain * T.get_orientation_error(desired_quaternion, current_quaternion) / 0.5,
        -1.0, 1.0,
    )
    return np.r_[position, orientation, np.clip(gripper, -1.0, 1.0)].astype(np.float32)


def closed_loop_trajectory(
    env, source: h5py.Group, mapping: TaskMapping, invert_gripper: bool,
    corrections_per_target: int, terminal_corrections: int,
    position_tolerance: float, orientation_tolerance: float, tracking_gain: float,
    pregrasp_corrections: int, gripper_transition_steps: int,
) -> dict[str, Any]:
    """Track the source TCP path with feedback through the evaluation wrapper."""
    source_actions = np.asarray(source["actions"], dtype=np.float32)
    articulation = source_articulation_states(source)
    actors = source_actor_states(source)
    if len(articulation) != len(source_actions) + 1:
        raise ValueError("closed-loop rollout requires one more state than action")

    env.reset()
    set_mapped_state(
        env, articulation[0], {name: value[0] for name, value in actors.items()},
        mapping.object_map,
    )
    robot = env.robots[0]
    robot.controller.update_initial_joints(
        np.asarray(robot._joint_positions, dtype=np.float64).copy()
    )
    robot.controller.reset_goal()
    desired_positions, desired_quaternions = reference_tcp_poses(env, articulation)
    wrapper = ManiSkillWrapper(env)
    states, observations, next_observations, commands = [], [], [], []
    rewards, dones, tracking_errors = [], [], []
    current_obs = env._get_observations(force_update=True)

    targets = list(range(1, len(articulation)))
    previous_source_gripper = float(source_actions[0, 7]) if source_actions.shape[1] > 7 else 1.0
    for target_index in targets:
        source_index = min(target_index - 1, len(source_actions) - 1)
        source_gripper = float(source_actions[source_index, 7]) if source_actions.shape[1] > 7 else 1.0
        gripper = -source_gripper if invert_gripper else source_gripper
        changed_gripper = not np.isclose(source_gripper, previous_source_gripper)
        phases = []
        if changed_gripper:
            previous_gripper = -previous_source_gripper if invert_gripper else previous_source_gripper
            phases.append((previous_gripper, pregrasp_corrections, True))
            phases.append((gripper, gripper_transition_steps, False))
        else:
            phases.append((gripper, corrections_per_target, False))
        for phase_gripper, phase_steps, stop_when_aligned in phases:
          for _ in range(phase_steps):
            command = osc_pose_action(
                current_obs, desired_positions[target_index], desired_quaternions[target_index], phase_gripper,
                tracking_gain,
            )
            states.append(np.asarray(wrapper.sim.get_state().flatten(), dtype=np.float64))
            observations.append(numeric_observation(current_obs, env))
            next_obs, reward, done, _ = wrapper.step(command)
            next_observations.append(numeric_observation(next_obs, env))
            commands.append(command)
            rewards.append(float(reward))
            dones.append(bool(done))
            position_error = desired_positions[target_index] - np.asarray(next_obs["robot0_eef_pos"])
            orientation_error = T.get_orientation_error(
                desired_quaternions[target_index], np.asarray(next_obs["robot0_eef_quat"])
            )
            tracking_errors.append(np.r_[position_error, orientation_error].astype(np.float32))
            current_obs = next_obs
            if wrapper.check_success():
                break
            if stop_when_aligned and (
                np.linalg.norm(position_error) <= position_tolerance
                and np.linalg.norm(orientation_error) <= orientation_tolerance
            ):
                break
          if wrapper.check_success():
              break
        previous_source_gripper = source_gripper
        if wrapper.check_success():
            break

    # Allow the controller and task objects to settle while continuing to
    # correct toward the final reference pose.
    if not wrapper.check_success():
        source_gripper = float(source_actions[-1, 7]) if source_actions.shape[1] > 7 else 1.0
        gripper = -source_gripper if invert_gripper else source_gripper
        for _ in range(terminal_corrections):
            command = osc_pose_action(
                current_obs, desired_positions[-1], desired_quaternions[-1], gripper,
                tracking_gain,
            )
            states.append(np.asarray(wrapper.sim.get_state().flatten(), dtype=np.float64))
            observations.append(numeric_observation(current_obs, env))
            next_obs, reward, done, _ = wrapper.step(command)
            next_observations.append(numeric_observation(next_obs, env))
            commands.append(command)
            rewards.append(float(reward))
            dones.append(bool(done))
            position_error = desired_positions[-1] - np.asarray(next_obs["robot0_eef_pos"])
            orientation_error = T.get_orientation_error(
                desired_quaternions[-1], np.asarray(next_obs["robot0_eef_quat"])
            )
            tracking_errors.append(np.r_[position_error, orientation_error].astype(np.float32))
            current_obs = next_obs
            if wrapper.check_success():
                break

    return {
        "states": np.asarray(states), "actions": np.asarray(commands, dtype=np.float32),
        "source_actions": source_actions, "rewards": np.asarray(rewards, dtype=np.float32),
        "dones": np.asarray(dones, dtype=np.bool_),
        "tracking_error": np.asarray(tracking_errors, dtype=np.float32),
        "obs": observations, "next_obs": next_observations,
        "copied_objects": sum(name in actors for name, _ in mapping.object_map),
        "success": wrapper.check_success(),
    }


def joint_closed_loop_trajectory(
    env, source: h5py.Group, mapping: TaskMapping, invert_gripper: bool,
    max_joint_step: float, joint_tolerance: float, joint_corrections: int,
    terminal_corrections: int,
    surface_friction: float, finger_friction: float, contact_timeconstant: float,
    gripper_force_limit: float,
) -> dict[str, Any]:
    """Track interpolated recorded joint states with feedback in MuJoCo."""
    source_actions = np.asarray(source["actions"], dtype=np.float32)
    articulation = source_articulation_states(source)
    actors = source_actor_states(source)
    if len(articulation) != len(source_actions) + 1:
        raise ValueError("joint closed-loop rollout requires states = actions + 1")

    env.reset()
    configure_contact_physics(
        env, surface_friction, finger_friction, contact_timeconstant, gripper_force_limit
    )
    set_mapped_state(
        env, articulation[0], {name: value[0] for name, value in actors.items()},
        mapping.object_map,
    )
    robot = env.robots[0]
    robot.controller.reset_goal()
    wrapper = ManiSkillWrapper(env)
    current_obs = env._get_observations(force_update=True)
    states, observations, next_observations, commands = [], [], [], []
    rewards, dones, tracking_errors = [], [], []

    def execute(target: np.ndarray, gripper: float, attempts: int) -> bool:
        nonlocal current_obs
        for _ in range(attempts):
            current = np.asarray(robot._joint_positions, dtype=np.float64)
            arm = scaled_joint_action(robot.controller, target, current)
            command = np.r_[arm, np.clip(gripper, -1.0, 1.0)].astype(np.float32)
            states.append(np.asarray(wrapper.sim.get_state().flatten(), dtype=np.float64))
            observations.append(numeric_observation(current_obs, env))
            next_obs, reward, done, _ = wrapper.step(command)
            next_observations.append(numeric_observation(next_obs, env))
            commands.append(command)
            rewards.append(float(reward))
            dones.append(bool(done))
            error = target - np.asarray(robot._joint_positions, dtype=np.float64)
            tracking_errors.append(error.astype(np.float32))
            current_obs = next_obs
            if wrapper.check_success() or np.max(np.abs(error)) <= joint_tolerance:
                break
        return wrapper.check_success()

    initial_reference = np.asarray(articulation[0, 13:20], dtype=np.float64)
    references = np.asarray(source_actions[:, :7], dtype=np.float64)
    for index, end in enumerate(references):
        start = initial_reference if index == 0 else references[index - 1]
        subdivisions = max(1, int(np.ceil(np.max(np.abs(end - start)) / max_joint_step)))
        source_gripper = float(source_actions[index, 7]) if source_actions.shape[1] > 7 else 1.0
        gripper = -source_gripper if invert_gripper else source_gripper
        for fraction in np.linspace(1.0 / subdivisions, 1.0, subdivisions):
            if execute(start + fraction * (end - start), gripper, joint_corrections):
                break
        if wrapper.check_success():
            break

    if not wrapper.check_success():
        source_gripper = float(source_actions[-1, 7]) if source_actions.shape[1] > 7 else 1.0
        gripper = -source_gripper if invert_gripper else source_gripper
        execute(references[-1], gripper, terminal_corrections)

    return {
        "states": np.asarray(states), "actions": np.asarray(commands, dtype=np.float32),
        "source_actions": source_actions, "rewards": np.asarray(rewards, dtype=np.float32),
        "dones": np.asarray(dones, dtype=np.bool_),
        "tracking_error": np.asarray(tracking_errors, dtype=np.float32),
        "obs": observations, "next_obs": next_observations,
        "copied_objects": sum(name in actors for name, _ in mapping.object_map),
        "success": wrapper.check_success(),
    }


def quaternion_distance_wxyz(a: np.ndarray, b: np.ndarray) -> float:
    """Unsigned angular distance between two wxyz quaternions."""
    a = np.asarray(a, dtype=np.float64)
    b = np.asarray(b, dtype=np.float64)
    a /= np.linalg.norm(a)
    b /= np.linalg.norm(b)
    return float(2.0 * np.arccos(np.clip(abs(np.dot(a, b)), 0.0, 1.0)))


def snapshot_rollout_state(env) -> dict[str, Any]:
    """Capture simulator and hidden controller state for MPC branching."""
    robot = env.robots[0]
    return {
        "sim": np.asarray(env.sim.get_state().flatten(), dtype=np.float64),
        "ctrl": np.asarray(env.sim.data.ctrl, dtype=np.float64).copy(),
        "goal_qpos": None
        if robot.controller.goal_qpos is None
        else np.asarray(robot.controller.goal_qpos, dtype=np.float64).copy(),
        "gripper_action": np.asarray(robot.gripper.current_action, dtype=np.float64).copy(),
        "cur_time": float(env.cur_time),
        "timestep": int(env.timestep),
    }


def restore_rollout_state(env, state: dict[str, Any]) -> None:
    """Restore a branch without leaking candidate controller state."""
    robot = env.robots[0]
    env.sim.set_state_from_flattened(state["sim"])
    env.sim.data.ctrl[:] = state["ctrl"]
    env.sim.forward()
    robot.controller.goal_qpos = (
        None if state["goal_qpos"] is None else state["goal_qpos"].copy()
    )
    robot.controller.new_update = True
    robot.gripper.current_action = state["gripper_action"].copy()
    env.cur_time = state["cur_time"]
    env.timestep = state["timestep"]


def mpc_tracking_cost(
    env,
    articulation: np.ndarray,
    actors: dict[str, np.ndarray],
    mapping: TaskMapping,
    source_index: int,
) -> float:
    """Shared dimensionless robot and object tracking cost."""
    robot = env.robots[0]
    target_state = articulation[source_index + 1]
    joint_error = np.asarray(robot._joint_positions) - target_state[13:20]
    velocity_error = np.asarray(robot._joint_velocities) - target_state[22:29]
    cost = float(np.mean((joint_error / 0.02) ** 2))
    cost += 0.05 * float(np.mean((velocity_error / 0.5) ** 2))
    for source_name, target_name in mapping.object_map:
        if target_name not in env.dynamic_object_names or source_name not in actors:
            continue
        actual = np.asarray(env.get_task_object_pose(target_name), dtype=np.float64)
        desired = np.asarray(actors[source_name][source_index + 1, :7], dtype=np.float64).copy()
        desired[:3] += np.asarray(env.source_world_offset, dtype=np.float64)
        cost += float((np.linalg.norm(actual[:3] - desired[:3]) / 0.01) ** 2)
        cost += float((quaternion_distance_wxyz(actual[3:7], desired[3:7]) / 0.1) ** 2)
    if env._check_success():
        cost -= 1000.0
    return cost


def mpc_joint_closed_loop_trajectory(
    env,
    source: h5py.Group,
    mapping: TaskMapping,
    invert_gripper: bool,
    terminal_corrections: int,
    surface_friction: float,
    finger_friction: float,
    contact_timeconstant: float,
    gripper_force_limit: float,
    mpc_samples: int,
    mpc_horizon: int,
    mpc_noise: float,
    mpc_seed: int,
) -> dict[str, Any]:
    """Retarget a source trajectory using receding-horizon command sampling."""
    source_actions = np.asarray(source["actions"], dtype=np.float32)
    articulation = source_articulation_states(source)
    actors = source_actor_states(source)
    env.reset()
    configure_contact_physics(
        env, surface_friction, finger_friction, contact_timeconstant, gripper_force_limit
    )
    set_mapped_state(
        env, articulation[0], {name: value[0] for name, value in actors.items()},
        mapping.object_map,
    )
    robot = env.robots[0]
    robot.controller.reset_goal()
    wrapper = ManiSkillWrapper(env)
    rng = np.random.default_rng(mpc_seed)
    current_obs = env._get_observations(force_update=True)
    states, observations, next_observations, commands = [], [], [], []
    rewards, dones, tracking_errors = [], [], []

    for index in range(len(source_actions)):
        branch = snapshot_rollout_state(env)
        best_cost = np.inf
        best_command = None
        residuals = np.zeros((mpc_samples, mpc_horizon, 7), dtype=np.float64)
        pair_count = (mpc_samples - 1) // 2
        if pair_count:
            noise = rng.normal(0.0, mpc_noise, size=(pair_count, mpc_horizon, 7))
            residuals[1 : 1 + pair_count] = noise
            residuals[1 + pair_count : 1 + 2 * pair_count] = -noise
        if 1 + 2 * pair_count < mpc_samples:
            residuals[-1] = rng.normal(0.0, mpc_noise, size=(mpc_horizon, 7))

        for candidate in range(mpc_samples):
            restore_rollout_state(env, branch)
            candidate_cost = 0.0
            first_command = None
            for horizon_step in range(mpc_horizon):
                future = min(index + horizon_step, len(source_actions) - 1)
                current = np.asarray(robot._joint_positions, dtype=np.float64)
                nominal = scaled_joint_action(
                    robot.controller, source_actions[future, :7], current
                )
                arm = np.clip(nominal + residuals[candidate, horizon_step], -1.0, 1.0)
                source_gripper = float(source_actions[future, 7])
                gripper = -source_gripper if invert_gripper else source_gripper
                command = np.r_[arm, np.clip(gripper, -1.0, 1.0)].astype(np.float32)
                if first_command is None:
                    first_command = command.copy()
                wrapper.step(command)
                if not (
                    np.all(np.isfinite(env.sim.data.qpos))
                    and np.all(np.isfinite(env.sim.data.qvel))
                    and np.all(np.isfinite(env.sim.data.qacc))
                ):
                    candidate_cost = np.inf
                    break
                candidate_cost += mpc_tracking_cost(
                    env, articulation, actors, mapping, future
                )
                candidate_cost += 0.02 * float(np.mean(residuals[candidate, horizon_step] ** 2))
                if wrapper.check_success():
                    break
            if best_command is None or candidate_cost < best_cost:
                best_cost = candidate_cost
                best_command = first_command

        restore_rollout_state(env, branch)
        states.append(np.asarray(wrapper.sim.get_state().flatten(), dtype=np.float64))
        observations.append(numeric_observation(current_obs, env))
        next_obs, reward, done, _ = wrapper.step(best_command)
        next_observations.append(numeric_observation(next_obs, env))
        commands.append(best_command)
        rewards.append(float(reward))
        dones.append(bool(done))
        error = source_actions[index, :7] - np.asarray(robot._joint_positions)
        tracking_errors.append(error.astype(np.float32))
        current_obs = next_obs
        if wrapper.check_success():
            break

    if not wrapper.check_success():
        source_gripper = float(source_actions[-1, 7])
        gripper = -source_gripper if invert_gripper else source_gripper
        for _ in range(terminal_corrections):
            current = np.asarray(robot._joint_positions, dtype=np.float64)
            arm = scaled_joint_action(robot.controller, source_actions[-1, :7], current)
            command = np.r_[arm, np.clip(gripper, -1.0, 1.0)].astype(np.float32)
            states.append(np.asarray(wrapper.sim.get_state().flatten(), dtype=np.float64))
            observations.append(numeric_observation(current_obs, env))
            next_obs, reward, done, _ = wrapper.step(command)
            next_observations.append(numeric_observation(next_obs, env))
            commands.append(command)
            rewards.append(float(reward))
            dones.append(bool(done))
            tracking_errors.append(
                (source_actions[-1, :7] - np.asarray(robot._joint_positions)).astype(np.float32)
            )
            current_obs = next_obs
            if wrapper.check_success():
                break

    return {
        "states": np.asarray(states), "actions": np.asarray(commands, dtype=np.float32),
        "source_actions": source_actions, "rewards": np.asarray(rewards, dtype=np.float32),
        "dones": np.asarray(dones, dtype=np.bool_),
        "tracking_error": np.asarray(tracking_errors, dtype=np.float32),
        "obs": observations, "next_obs": next_observations,
        "copied_objects": sum(name in actors for name, _ in mapping.object_map),
        "success": wrapper.check_success(),
    }


def map_trajectory_states(
    env,
    source: h5py.Group,
    mapping: TaskMapping,
    invert_gripper: bool,
) -> dict[str, Any]:
    """Convert a trajectory without allowing simulator drift between samples."""
    source_actions = np.asarray(source["actions"], dtype=np.float32)
    articulation = source_articulation_states(source)
    actors = source_actor_states(source)
    sample_count = len(source_actions)
    if len(articulation) != sample_count + 1:
        raise ValueError(
            f"articulation states ({len(articulation)}) must equal actions + 1 "
            f"({sample_count + 1})"
        )
    for name, values in actors.items():
        if len(values) != sample_count + 1:
            raise ValueError(f"actor {name} has {len(values)} states, expected {sample_count + 1}")

    env.reset()
    states: list[np.ndarray] = []
    observations: list[dict[str, np.ndarray]] = []
    mapped_actions: list[np.ndarray] = []
    for index in range(sample_count + 1):
        set_mapped_state(
            env,
            articulation[index],
            {name: values[index] for name, values in actors.items()},
            mapping.object_map,
        )
        if index < sample_count:
            states.append(np.asarray(env.sim.get_state().flatten(), dtype=np.float64))
            observations.append(numeric_observation(env._get_observations(force_update=True), env))
            mapped_actions.append(
                retarget_action(env, source_actions[index], invert_gripper).astype(np.float32)
            )
        else:
            final_observation = numeric_observation(
                env._get_observations(force_update=True), env
            )

    source_rewards = np.asarray(source.get("rewards", np.zeros(sample_count)), dtype=np.float32)
    terminated = np.asarray(source.get("terminated", np.zeros(sample_count)), dtype=np.bool_)
    truncated = np.asarray(source.get("truncated", np.zeros(sample_count)), dtype=np.bool_)
    return {
        "states": np.asarray(states),
        "actions": np.asarray(mapped_actions),
        "source_actions": source_actions,
        "rewards": source_rewards,
        "dones": np.logical_or(terminated, truncated),
        "tracking_error": np.zeros((sample_count, 7), dtype=np.float32),
        "obs": observations,
        "next_obs": observations[1:] + [final_observation],
        "copied_objects": sum(name in actors for name, _ in mapping.object_map),
    }


def output_env_metadata(env, env_name: str, control_freq: int) -> str:
    try:
        return json.dumps(env.serialize(), sort_keys=True)
    except (AttributeError, TypeError):
        return json.dumps(
            {
                "env_name": env_name,
                "type": 1,
                "env_kwargs": {
                    "robots": ["Panda"],
                    "controller_configs": load_controller_config(
                        default_controller="JOINT_POSITION"
                    ),
                    "gripper_types": "PandaGripper",
                    "use_camera_obs": False,
                    "use_object_obs": True,
                    "reward_shaping": False,
                    "control_freq": control_freq,
                },
            },
            sort_keys=True,
        )


def convert(args: argparse.Namespace) -> None:
    input_path = args.input.resolve()
    if not input_path.is_file():
        raise FileNotFoundError(input_path)
    task_id = args.task_id or task_id_from_path(input_path)
    mapping = TASK_MAPPINGS.get(task_id)
    if mapping is None:
        raise ValueError(
            f"no default mapping for {task_id}; supported: {', '.join(TASK_MAPPINGS)}"
        )
    if args.env_name:
        mapping = TaskMapping(args.env_name, mapping.object_map, "user_override")

    metadata = source_episode_metadata(input_path.with_suffix(".json"))
    controller = "OSC_POSE" if args.conversion_mode == "closed-loop" else "JOINT_POSITION"
    joint_modes = ("joint-closed-loop", "mpc-joint-closed-loop")
    joint_kp = args.joint_kp if args.conversion_mode in joint_modes else None
    joint_damping = (
        args.joint_damping_ratio if args.conversion_mode in joint_modes else None
    )
    env = make_environment(
        mapping.env_name, args.control_freq, controller=controller,
        joint_kp=joint_kp, joint_damping_ratio=joint_damping,
    )
    output_path = args.output.resolve()
    output_path.parent.mkdir(parents=True, exist_ok=True)
    temporary_path = output_path.with_name(f".{output_path.name}.tmp")
    if temporary_path.exists():
        temporary_path.unlink()

    total = 0
    try:
        with h5py.File(input_path, "r") as source_file, h5py.File(temporary_path, "w") as output_file:
            data = output_file.create_group("data")
            data.attrs["env_args"] = output_env_metadata(
                env, mapping.env_name, args.control_freq
            )
            data.attrs["env_meta"] = data.attrs["env_args"]
            data.attrs["source_task"] = task_id
            data.attrs["target_env"] = mapping.env_name
            data.attrs["environment_label"] = getattr(
                env, "environment_label", mapping.env_name
            )
            data.attrs["environment_family"] = "maniskill_mujoco_port"
            data.attrs["retarget_fidelity"] = mapping.fidelity
            data.attrs["source_file"] = str(input_path)
            data.attrs["wrench_frame"] = "robosuite Panda gripper force/torque sensor frame"
            data.attrs["wrench_units"] = "N,Nm"
            data.attrs["cross_simulation"] = True
            data.attrs["conversion_mode"] = args.conversion_mode
            data.attrs["state_alignment"] = {
                "state-map": "recorded_maniskill_states_mapped_to_mujoco",
                "replay": "open_loop_mujoco_replay",
                "closed-loop": "closed_loop_tcp_tracking_in_mujoco",
                "joint-closed-loop": "interpolated_closed_loop_joint_tracking_in_mujoco",
                "mpc-joint-closed-loop": "receding_horizon_joint_and_object_tracking_in_mujoco",
            }[args.conversion_mode]
            data.attrs["controller"] = controller
            if args.conversion_mode == "mpc-joint-closed-loop":
                data.attrs["mpc_samples"] = args.mpc_samples
                data.attrs["mpc_horizon"] = args.mpc_horizon
                data.attrs["mpc_noise"] = args.mpc_noise
                data.attrs["mpc_seed"] = args.mpc_seed
                data.attrs["mpc_restarts"] = args.mpc_restarts

            keys = sorted(
                (key for key in source_file if key.startswith("traj_")),
                key=natural_trajectory_key,
            )
            if args.count is not None:
                keys = keys[: args.count]
            if not keys:
                raise ValueError(f"no traj_* groups found in {input_path}")

            accepted = 0
            rejected = 0
            for source_key in keys:
                episode_id = int(source_key.rsplit("_", 1)[1])
                episode_metadata = metadata.get(episode_id, {})
                if hasattr(env, "configure_source_episode"):
                    env.configure_source_episode(episode_metadata)
                if args.conversion_mode == "state-map":
                    result = map_trajectory_states(
                        env,
                        source_file[source_key],
                        mapping,
                        invert_gripper=not args.no_invert_gripper,
                    )
                elif args.conversion_mode == "replay":
                    result = replay_trajectory(
                        env,
                        source_file[source_key],
                        mapping,
                        invert_gripper=not args.no_invert_gripper,
                        copy_object_poses=not args.no_copy_object_poses,
                    )
                elif args.conversion_mode == "closed-loop":
                    result = closed_loop_trajectory(
                        env, source_file[source_key], mapping,
                        invert_gripper=not args.no_invert_gripper,
                        corrections_per_target=args.corrections_per_target,
                        terminal_corrections=args.terminal_corrections,
                        position_tolerance=args.position_tolerance,
                        orientation_tolerance=args.orientation_tolerance,
                        tracking_gain=args.tracking_gain,
                        pregrasp_corrections=args.pregrasp_corrections,
                        gripper_transition_steps=args.gripper_transition_steps,
                    )
                elif args.conversion_mode == "joint-closed-loop":
                    result = joint_closed_loop_trajectory(
                        env, source_file[source_key], mapping,
                        invert_gripper=not args.no_invert_gripper,
                        max_joint_step=args.max_joint_step,
                        joint_tolerance=args.joint_tolerance,
                        joint_corrections=args.joint_corrections,
                        terminal_corrections=args.terminal_corrections,
                        surface_friction=args.surface_friction,
                        finger_friction=args.finger_friction,
                        contact_timeconstant=args.contact_timeconstant,
                        gripper_force_limit=args.gripper_force_limit,
                    )
                else:
                    for restart in range(args.mpc_restarts):
                        result = mpc_joint_closed_loop_trajectory(
                            env, source_file[source_key], mapping,
                            invert_gripper=not args.no_invert_gripper,
                            terminal_corrections=args.terminal_corrections,
                            surface_friction=args.surface_friction,
                            finger_friction=args.finger_friction,
                            contact_timeconstant=args.contact_timeconstant,
                            gripper_force_limit=args.gripper_force_limit,
                            mpc_samples=args.mpc_samples,
                            mpc_horizon=args.mpc_horizon,
                            mpc_noise=args.mpc_noise,
                            mpc_seed=args.mpc_seed + episode_id + 1_000_003 * restart,
                        )
                        if result["success"]:
                            break
                    result["mpc_attempt"] = restart
                rollout_failed = (
                    args.conversion_mode in ("closed-loop", *joint_modes)
                    and not result["success"]
                )
                if rollout_failed:
                    rejected += 1
                    final_error = np.max(np.abs(result["tracking_error"][-1]))
                    print(
                        f"{source_key}: rejected (task did not succeed; "
                        f"final tracking error={final_error:.4f}, "
                        f"max reward={np.max(result['rewards']):.3f})"
                    )
                    if not args.keep_failures:
                        continue
                demo = data.create_group(f"demo_{accepted}")
                result["mujoco_joint_actions"] = result["actions"]
                if args.conversion_mode not in ("closed-loop", *joint_modes):
                    result["actions"] = libero_actions(result)
                robot_states = np.stack(
                    [np.concatenate((obs["joint_states"], obs["gripper_states"])) for obs in result["obs"]]
                )
                result["robot_states"] = robot_states.astype(np.float32)
                for key in (
                    "states", "actions", "mujoco_joint_actions", "source_actions",
                    "robot_states", "rewards", "dones", "tracking_error",
                ):
                    demo.create_dataset(key, data=result[key], compression="gzip")
                write_observation_group(demo, "obs", result["obs"])
                write_observation_group(demo, "next_obs", result["next_obs"])
                samples = len(result["actions"])
                demo.attrs["num_samples"] = samples
                demo.attrs["source_trajectory"] = source_key
                demo.attrs["source_episode_metadata"] = json.dumps(
                    episode_metadata, sort_keys=True
                )
                demo.attrs["copied_source_object_poses"] = result["copied_objects"]
                demo.attrs["successful"] = not rollout_failed
                if "mpc_attempt" in result:
                    demo.attrs["mpc_attempt"] = result["mpc_attempt"]
                try:
                    demo.attrs["model_file"] = env.model.get_xml()
                except AttributeError:
                    pass
                total += samples
                accepted += 1
                if args.conversion_mode == "replay":
                    detail = f", max joint error={np.max(np.abs(result['tracking_error'])):.4f} rad"
                else:
                    detail = ""
                print(f"{source_key} -> demo_{accepted - 1}: {samples} steps{detail}")
                if args.target_successes is not None and accepted >= args.target_successes:
                    break

            data.attrs["total"] = total
            data.attrs["num_demos"] = accepted
            data.attrs["rejected_demos"] = rejected
            output_file.flush()
        os.replace(temporary_path, output_path)
    except BaseException:
        if temporary_path.exists():
            temporary_path.unlink()
        raise
    finally:
        env.close()

    label = "diagnostic demos" if args.keep_failures else "successful demos"
    print(f"Wrote {accepted} {label} / {total} samples to {output_path} ({rejected} rejected)")
    if mapping.fidelity != "procedural_port":
        print(f"WARNING: {task_id} uses {mapping.env_name} with fidelity={mapping.fidelity}")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", type=Path, required=True, help="ManiSkill trajectory.h5")
    parser.add_argument("--output", type=Path, required=True, help="Output robomimic HDF5")
    parser.add_argument("--task-id", help="Override task inferred from the input path")
    parser.add_argument("--env-name", help="Override the mapped robosuite environment")
    parser.add_argument("--count", type=int, help="Only convert the first N trajectories")
    parser.add_argument(
        "--target-successes", type=int,
        help="Stop scanning source trajectories after retaining this many successes",
    )
    parser.add_argument("--control-freq", type=int, default=20)
    parser.add_argument(
        "--conversion-mode",
        choices=(
            "state-map", "replay", "closed-loop", "joint-closed-loop",
            "mpc-joint-closed-loop",
        ),
        default="state-map",
        help="Map recorded states, test open-loop replay, or track TCP poses closed-loop",
    )
    parser.add_argument(
        "--corrections-per-target", type=int, default=1,
        help="Maximum feedback steps used to converge to each reference TCP pose",
    )
    parser.add_argument(
        "--terminal-corrections", type=int, default=20,
        help="Extra feedback steps toward the final TCP pose in closed-loop mode",
    )
    parser.add_argument("--position-tolerance", type=float, default=0.005)
    parser.add_argument("--orientation-tolerance", type=float, default=0.05)
    parser.add_argument("--tracking-gain", type=float, default=1.0)
    parser.add_argument("--pregrasp-corrections", type=int, default=1)
    parser.add_argument("--gripper-transition-steps", type=int, default=1)
    parser.add_argument("--max-joint-step", type=float, default=0.05)
    parser.add_argument("--joint-tolerance", type=float, default=0.01)
    parser.add_argument("--joint-corrections", type=int, default=1)
    parser.add_argument("--joint-kp", type=float, default=500.0)
    parser.add_argument("--joint-damping-ratio", type=float, default=1.58113883)
    parser.add_argument("--mpc-samples", type=int, default=9)
    parser.add_argument("--mpc-horizon", type=int, default=3)
    parser.add_argument("--mpc-noise", type=float, default=0.08)
    parser.add_argument("--mpc-seed", type=int, default=0)
    parser.add_argument(
        "--mpc-restarts", type=int, default=1,
        help="Independent deterministic MPC attempts per source trajectory",
    )
    parser.add_argument("--surface-friction", type=float, default=0.5)
    parser.add_argument("--finger-friction", type=float, default=2.0)
    parser.add_argument("--contact-timeconstant", type=float, default=0.002)
    parser.add_argument("--gripper-force-limit", type=float, default=100.0)
    parser.add_argument(
        "--keep-failures", action="store_true",
        help="Diagnostic only: write failed rollouts instead of filtering them",
    )
    parser.add_argument(
        "--no-invert-gripper",
        action="store_true",
        help="Do not map ManiSkill +1=open to robosuite -1=open",
    )
    parser.add_argument(
        "--no-copy-object-poses",
        action="store_true",
        help="Keep robosuite's sampled initial object poses",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    if args.count is not None and args.count <= 0:
        raise ValueError("--count must be positive")
    if args.target_successes is not None and args.target_successes <= 0:
        raise ValueError("--target-successes must be positive")
    if args.corrections_per_target <= 0 or args.terminal_corrections < 0:
        raise ValueError("correction counts must be positive / non-negative")
    if args.position_tolerance <= 0 or args.orientation_tolerance <= 0 or args.tracking_gain <= 0:
        raise ValueError("tracking tolerances must be positive")
    if args.pregrasp_corrections <= 0 or args.gripper_transition_steps <= 0:
        raise ValueError("gripper synchronization step counts must be positive")
    if args.max_joint_step <= 0 or args.joint_tolerance <= 0 or args.joint_corrections <= 0:
        raise ValueError("joint tracking parameters must be positive")
    if args.joint_kp <= 0 or args.joint_damping_ratio <= 0:
        raise ValueError("joint controller gains must be positive")
    if (
        args.mpc_samples <= 0 or args.mpc_horizon <= 0 or args.mpc_noise <= 0
        or args.mpc_restarts <= 0
    ):
        raise ValueError("MPC sampling parameters must be positive")
    if args.surface_friction <= 0 or args.finger_friction <= 0 or args.contact_timeconstant <= 0:
        raise ValueError("contact parameters must be positive")
    if args.gripper_force_limit <= 0:
        raise ValueError("gripper force limit must be positive")
    convert(args)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
